theme = "one_transparent"

[editor]
mouse = false
shell = ["zsh", "-c"]
line-number = "relative"
auto-format = true
completion-timeout = 5
color-modes = true

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = false

[editor.cursor-shape]
insert = "bar"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
